
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MNArifin
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etNama = new javax.swing.JTextField();
        etId = new javax.swing.JTextField();
        etHarga = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        etHarga1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        etNama1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etId1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etId2 = new javax.swing.JTextField();
        etNama2 = new javax.swing.JTextField();
        etHarga2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        etTHarga = new javax.swing.JTextField();
        etJBarang = new javax.swing.JTextField();
        etNKasir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKasir = new javax.swing.JTable();
        bPrint = new javax.swing.JButton();
        bTransaksi = new javax.swing.JButton();
        dcTglLahir = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        etDiskon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        tBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nama", "Harga"
            }
        ));
        tBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tBarang);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 10, 510, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(330, 60, 560, 280);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID Barang");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 0, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nama Barang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 60, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Harga Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 120, 220, 30);

        etNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNamaActionPerformed(evt);
            }
        });
        jPanel2.add(etNama);
        etNama.setBounds(40, 90, 220, 30);

        etId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etIdActionPerformed(evt);
            }
        });
        jPanel2.add(etId);
        etId.setBounds(40, 30, 220, 30);

        etHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etHargaActionPerformed(evt);
            }
        });
        jPanel2.add(etHarga);
        etHarga.setBounds(40, 150, 220, 30);

        bSave.setText("Tambah Barang");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel2.add(bSave);
        bSave.setBounds(40, 200, 107, 23);

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(bDelete);
        bDelete.setBounds(190, 200, 70, 23);

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel2.add(bClear);
        bClear.setBounds(40, 240, 70, 23);

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(bRefresh);
        bRefresh.setBounds(190, 250, 70, 23);

        etHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etHarga1ActionPerformed(evt);
            }
        });
        jPanel2.add(etHarga1);
        etHarga1.setBounds(40, 150, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Harga Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 120, 220, 30);

        etNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNama1ActionPerformed(evt);
            }
        });
        jPanel2.add(etNama1);
        etNama1.setBounds(40, 90, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nama Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 60, 220, 30);

        etId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etId1ActionPerformed(evt);
            }
        });
        jPanel2.add(etId1);
        etId1.setBounds(40, 30, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ID Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 0, 220, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 310, 280);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KASIR E MBOK MU");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 0, 640, 50);

        Tanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Tanggal);
        Tanggal.setBounds(650, 10, 120, 30);

        Jam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Jam);
        Jam.setBounds(780, 10, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 890, 50);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("ID Barang");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 0, 220, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Nama Barang");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 50, 220, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Harga Barang");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 100, 220, 20);

        etId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etId2ActionPerformed(evt);
            }
        });
        jPanel4.add(etId2);
        etId2.setBounds(40, 20, 220, 30);

        etNama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNama2ActionPerformed(evt);
            }
        });
        jPanel4.add(etNama2);
        etNama2.setBounds(40, 70, 220, 30);

        etHarga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etHarga2ActionPerformed(evt);
            }
        });
        jPanel4.add(etHarga2);
        etHarga2.setBounds(40, 120, 220, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Jumlah Barang");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(40, 150, 220, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Total Harga");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 200, 220, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Nama Kasir");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(310, 0, 220, 20);

        etTHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etTHargaActionPerformed(evt);
            }
        });
        jPanel4.add(etTHarga);
        etTHarga.setBounds(40, 220, 220, 30);

        etJBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etJBarangActionPerformed(evt);
            }
        });
        jPanel4.add(etJBarang);
        etJBarang.setBounds(40, 170, 220, 30);

        etNKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNKasirActionPerformed(evt);
            }
        });
        jPanel4.add(etNKasir);
        etNKasir.setBounds(310, 20, 220, 30);

        tKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Harga", "Jumlah", "TotalHarga", "Kasir", "Tanggal", "Diskon"
            }
        ));
        jScrollPane1.setViewportView(tKasir);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(360, 180, 450, 100);

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel4.add(bPrint);
        bPrint.setBounds(740, 290, 70, 23);

        bTransaksi.setText("Simpan Transaksi");
        bTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransaksiActionPerformed(evt);
            }
        });
        jPanel4.add(bTransaksi);
        bTransaksi.setBounds(360, 300, 120, 23);
        jPanel4.add(dcTglLahir);
        dcTglLahir.setBounds(310, 70, 220, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tanggal Transaksi");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(310, 50, 220, 20);

        etDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etDiskonActionPerformed(evt);
            }
        });
        jPanel4.add(etDiskon);
        etDiskon.setBounds(310, 120, 220, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Diskon");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(310, 100, 220, 20);

        bLoad.setText("Load");
        bLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadActionPerformed(evt);
            }
        });
        jPanel4.add(bLoad);
        bLoad.setBounds(570, 290, 55, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 360, 890, 410);

        setBounds(0, 0, 907, 808);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:

        if (etId.getText().equals("")||
            etNama.getText().equals("")||
            etHarga.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            String SQL = "insert into t_barang (id_barang,nm_barang,hrg_barang)"
            + "values ('"+etId.getText()+"','"+etNama.getText()+"','"+etHarga.getText()+"')";
            int status = koneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tBarang.getSelectedRow();
        if (baris >= 0)
        {
            String Id = tBarang.getValueAt(baris, 0).toString();
            String SQL = "delete from t_siswa where id_barang='"+Id+"'";
            int status = koneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        etId.setText("");
        etNama.setText("");
        etHarga.setText("");

    }//GEN-LAST:event_bClearActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void tBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBarangMouseClicked
        // TODO add your handling code here:
        int baris = tBarang.getSelectedRow();
        if (baris != -1)
        {
            etId2.setText(tBarang.getValueAt(baris, 0).toString());
            etNama2.setText(tBarang.getValueAt(baris, 1).toString());
            etHarga2.setText(tBarang.getValueAt(baris, 2).toString());
            etJBarang.setText("");
            etTHarga.setText("");
            etNKasir.setText("");
            etDiskon.setText("");
        }
    }//GEN-LAST:event_tBarangMouseClicked

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Struk Pembelian");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try
        {
            tBarang.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void etNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNamaActionPerformed

    private void etIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etIdActionPerformed

    private void etHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etHargaActionPerformed

    private void etHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etHarga1ActionPerformed

    private void etNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNama1ActionPerformed

    private void etId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etId1ActionPerformed

    private void etNama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNama2ActionPerformed

    private void etId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etId2ActionPerformed

    private void etHarga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etHarga2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etHarga2ActionPerformed

    private void etTHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etTHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etTHargaActionPerformed

    private void etJBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etJBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etJBarangActionPerformed

    private void etNKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNKasirActionPerformed

    private void bTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransaksiActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(dcTglLahir.getDate());
        
        if (etId2.getText().equals("")||
            etNama2.getText().equals("")||
            etHarga2.getText().equals("")||
            etJBarang.getText().equals("")||
            etTHarga.getText().equals("")||
            etNKasir.getText().equals("")||
            etDiskon.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            String SQL = "insert into t_transaksi (id_barang,nm_barang,hrg_barang,jml_barang,ttl_harga,nm_kasir,tgl_transaksi,diskon)"
            + "values ('"+etId2.getText()+"','"+etNama2.getText()+"','"+etHarga2.getText()+"','"+etJBarang.getText()+"','"+etTHarga.getText()+"','"+etNKasir.getText()+"','"+tanggal+"','"+etDiskon.getText()+"')";
            int status = koneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bTransaksiActionPerformed

    private void etDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etDiskonActionPerformed

    private void bLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_bLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jam;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bLoad;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bTransaksi;
    private com.toedter.calendar.JDateChooser dcTglLahir;
    private javax.swing.JTextField etDiskon;
    private javax.swing.JTextField etHarga;
    private javax.swing.JTextField etHarga1;
    private javax.swing.JTextField etHarga2;
    private javax.swing.JTextField etId;
    private javax.swing.JTextField etId1;
    private javax.swing.JTextField etId2;
    private javax.swing.JTextField etJBarang;
    private javax.swing.JTextField etNKasir;
    private javax.swing.JTextField etNama;
    private javax.swing.JTextField etNama1;
    private javax.swing.JTextField etNama2;
    private javax.swing.JTextField etTHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tBarang;
    private javax.swing.JTable tKasir;
    // End of variables declaration//GEN-END:variables

    private void selectData()
    {
        String kolom[] = {"id_barang","nm_barang","hrg_barang"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_barang";
        ResultSet rs = koneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next()) 
            {
                String id_barang = rs.getString(1);
                String nm_barang = rs.getString(2);
                String hrg_barang = rs.getString(3);
                String data[] = {id_barang,nm_barang,hrg_barang};
                dtm.addRow(data);
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        tBarang.setModel(dtm);
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Tanggal.setText(kal.format(skrg));
    }

    private void loadData() 
    {
        String kolom[] = {"id_barang","nm_barang","hrg_barang","jml_barang","ttl_harga","nm_kasir","tgl_transaksi","diskon"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_transaksi";
        ResultSet rs = koneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next()) 
            {
                String id_barang = rs.getString(1);
                String nm_barang = rs.getString(2);
                String hrg_barang = rs.getString(3);
                String jml_barang = rs.getString(4);
                String ttl_harga = rs.getString(5);
                String nm_kasir = rs.getString(6);
                String tgl_transaksi = rs.getString(7);
                String diskon = rs.getString(8);
                String data[] = {id_barang,nm_barang,hrg_barang,jml_barang,ttl_harga,nm_kasir,tgl_transaksi,diskon};
                dtm.addRow(data);
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        tKasir.setModel(dtm);
    }
}
